
-- CREATE SCHEMA ferd_transformator;

USE ferd_transformator;

CREATE TABLE Country (
Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(100) NULL,
Abbreviation VARCHAR(100) NULL,
CreatedDate TIMESTAMP,
ModifiedDate TIMESTAMP
);

CREATE TABLE CorporateForm (
Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(100) NULL,
ShortName VARCHAR(100) Null,
UsedInCountries INT(6) UNSIGNED Null,
CreatedDate TIMESTAMP,
ModifiedDate TIMESTAMP
);

CREATE TABLE Country_CorporateForm(
Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Country_Id INT(6) UNSIGNED NOT NULL,
CorporateForm_Id INT(6) UNSIGNED NOT NULL,
FOREIGN KEY (Country_Id) REFERENCES Country(Id) ON DELETE CASCADE,
FOREIGN KEY (CorporateForm_Id) REFERENCES CorporateForm(Id) ON DELETE CASCADE,
CreatedDate TIMESTAMP,
ModifiedDate TIMESTAMP
);

ALTER TABLE CorporateForm Add FOREIGN KEY (UsedInCountries) REFERENCES Country_CorporateForm(Id);

CREATE TABLE Address (
Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Street VARCHAR(100) NULL,
ZipCode INT(5) NULL,
City VARCHAR(100) NULL,
Country INT(6) UNSIGNED NULL,
CreatedDate TIMESTAMP,
ModifiedDate TIMESTAMP,
FOREIGN KEY (Country) REFERENCES Country(Id) ON DELETE CASCADE
);

CREATE TABLE LegalPerson (
Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
IsCompany BOOL NOT NULL,
CompanyName VARCHAR(100) NULL,
CorporateForm INT(6) UNSIGNED NULL,
Name VARCHAR(100) NULL,
FirstName VARCHAR(100) NULL,
Address INT(6) UNSIGNED NULL,
CreatedDate TIMESTAMP,
ModifiedDate TIMESTAMP,
FOREIGN KEY (CorporateForm) REFERENCES CorporateForm(Id) ON DELETE CASCADE,
FOREIGN KEY (Address) REFERENCES Address(Id) ON DELETE CASCADE
);

CREATE TABLE Invoice (
Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
-- Parties INT(6) UNSIGNED NULL,
Debitor INT(6) UNSIGNED NULL,
Creditor INT(6) UNSIGNED NULL,
InvoiceNumber VARCHAR(50) NULL,
IssueDate TIMESTAMP NULL,
DeliveryDate TIMESTAMP NULL,
LineTotal NUMERIC(15,2) NULL,
ChargeTotal NUMERIC(15,2) NULL,
AllowanceTotal NUMERIC(15,2) NULL,
TaxBasisTotal NUMERIC(15,2) NULL,
TaxTotal NUMERIC(15,2) NULL,
HasSkonto BOOL NULL,
Skonto NUMERIC(2,1) NULL,
GrandTotal NUMERIC(15,2) NULL,
CreatedDate TIMESTAMP,
ModifiedDate TIMESTAMP,
FOREIGN KEY (Debitor) REFERENCES LegalPerson(Id) ON DELETE CASCADE,
FOREIGN KEY (Creditor) REFERENCES LegalPerson(Id) ON DELETE CASCADE
);

-- CREATE TABLE LegalPerson_Invoice (
-- Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
-- LegalPerson_ID INT(6) UNSIGNED NOT NULL,
-- Invoice_ID INT(6) UNSIGNED NOT NULL,
-- IsDebitor BOOL NOT NULL,
-- CreatedDate TIMESTAMP,
-- ModifiedDate TIMESTAMP,
-- FOREIGN KEY (LegalPerson_ID) REFERENCES LegalPerson(Id) ON DELETE CASCADE,
-- FOREIGN KEY (Invoice_ID) REFERENCES Invoice(Id) ON DELETE CASCADE
-- );

-- ALTER TABLE Invoice ADD FOREIGN KEY (Parties) REFERENCES LegalPerson_Invoice(Id) ON DELETE CASCADE;

CREATE TABLE Scan (
Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
-- eventually needs to be longblob
File BLOB,
InvoiceInformation INT(6) UNSIGNED NULL,
CreatedDate TIMESTAMP,
ModifiedDate TIMESTAMP,
FOREIGN KEY (InvoiceInformation) REFERENCES Invoice(Id) ON DELETE CASCADE
);