CREATE TABLE LegalPerson_Invoice (
Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
LegalPerson_ID INT(6) UNSIGNED NOT NULL,
Invoice_ID INT(6) UNSIGNED NOT NULL,
IsDebitor BOOL NOT NULL,
CreatedDate TIMESTAMP,
ModifiedDate TIMESTAMP,
FOREIGN KEY (LegalPerson_ID) REFERENCES LegalPerson(Id) ON DELETE CASCADE,
FOREIGN KEY (Invoice_ID) REFERENCES Invoice(Id) ON DELETE CASCADE
);